---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: masterpro-deployment
  labels:
    app: masterpro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: masterpro  
  template:
    metadata:
      labels:
        app: masterpro  
    spec:
      containers: 
      - name: masterpro
        image: devopsproject1.azurecr.io/masterpro:latest
        ports:
        - containerPort: 8080 
         
...