---
apiVersion: v1
kind: Service
metadata:
  name: masterpro-service 
  labels:
    app: masterpro
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: masterpro
...